### ISSUE TITLE
cant be maxmimized

### ISSUE THREAD

**Issue by zombrax1** [ShivkalaDrakh/Hive-Organizer-for-Whiteout-Survival-State-of-Survival#2]
Dear sir , thank u for the tool is very nice i run it in windows however  , if i follow my trap location is 430x 600
while 600i cant see it on page is too down  and grid only max i can see on my pc is 540
![Screenshot 2024-10-28 152809](https://github.com/user-attachments/assets/c018fc9d-769a-4173-98ce-abc43d7c7984)

**Comment by ShivkalaDrakh** [comment]
Hi zombrax!

Thanks for your feedback! Trap grid location was introduced in V0.2:
![TrapCoordinates](https://github.com/user-attachments/assets/f2824c9c-6679-4e62-a59c-04be5cefaa09)
Just download the latest version, enter the coordinates of the Trap (in your case X: 430 Y: 647) in the circled field and it should solve the issue.

**Comment by zombrax1** [comment]
thanks man , for a second i felt dumb , didnt download latest , thanks for info it worked now good   still testing , however maybe can have history ?
example member A beside  location X and Y    i can know this member where was before we move there ? 
thank u again that was a big help Regards

**Comment by ShivkalaDrakh** [comment]
History is an interesting idea, hadn't thought of that! I'll check how easy (or not ;) ) that would be to implement
